"""add total_engagement to metrics_snapshots

Revision ID: 21c675a10fdb
Revises: 3c8d4a1e9f22
Create Date: 2026-02-05 18:10:58.683204

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c675a10fdb'
down_revision: str | Sequence[str] | None = '3c8d4a1e9f22'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_mentions_collected_at_title'),
        'mentions',
        ['collected_at', 'title_id'],
        unique=False,
    )
    op.add_column('metrics_snapshots', sa.Column('total_engagement', sa.Integer(), server_default='0', nullable=False))
    op.add_column('metrics_snapshots', sa.Column('negative_ratio', sa.Float(), nullable=True))
    op.create_index(op.f('ix_pipeline_runs_finished_at'), 'pipeline_runs', ['finished_at'], unique=False)

    # Drop indexes removed from models (no longer needed for query patterns).
    # ix_mentions_created_at: windowing now uses collected_at instead.
    # ix_leases_owner_id: leases table is tiny (single row); no benefit.
    # ix_pipeline_runs_job_name / owner_id: covered by composite indexes.
    op.drop_index(op.f('ix_mentions_created_at'), table_name='mentions')
    op.drop_index(op.f('ix_leases_owner_id'), table_name='leases')
    op.drop_index(op.f('ix_pipeline_runs_job_name'), table_name='pipeline_runs')
    op.drop_index(op.f('ix_pipeline_runs_owner_id'), table_name='pipeline_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pipeline_runs_owner_id'), 'pipeline_runs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pipeline_runs_job_name'), 'pipeline_runs', ['job_name'], unique=False)
    op.create_index(op.f('ix_leases_owner_id'), 'leases', ['owner_id'], unique=False)
    op.create_index(op.f('ix_mentions_created_at'), 'mentions', ['created_at'], unique=False)
    op.drop_index(op.f('ix_pipeline_runs_finished_at'), table_name='pipeline_runs')
    op.drop_column('metrics_snapshots', 'negative_ratio')
    op.drop_column('metrics_snapshots', 'total_engagement')
    op.drop_index(op.f('ix_mentions_collected_at_title'), table_name='mentions')
    # ### end Alembic commands ###
