"""Initial schema - titles mentions metrics alerts

Revision ID: 9408ea0bb59f
Revises:
Create Date: 2026-01-29 02:01:15.495868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9408ea0bb59f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('poster_path', sa.String(length=255), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titles_tmdb_id'), 'titles', ['tmdb_id'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_title_id'), 'alerts', ['title_id'], unique=False)
    op.create_table('mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'source_id', name='uq_platform_source')
    )
    op.create_index(op.f('ix_mentions_created_at'), 'mentions', ['created_at'], unique=False)
    op.create_index('ix_mentions_created_at_title', 'mentions', ['created_at', 'title_id'], unique=False)
    op.create_index(op.f('ix_mentions_title_id'), 'mentions', ['title_id'], unique=False)
    op.create_index('ix_mentions_title_platform', 'mentions', ['title_id', 'platform'], unique=False)
    op.create_table('metrics_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_hours', sa.Integer(), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('unique_authors', sa.Integer(), nullable=False),
    sa.Column('reddit_mentions', sa.Integer(), nullable=False),
    sa.Column('youtube_mentions', sa.Integer(), nullable=False),
    sa.Column('mention_velocity', sa.Float(), nullable=True),
    sa.Column('velocity_change', sa.Float(), nullable=True),
    sa.Column('avg_sentiment', sa.Float(), nullable=True),
    sa.Column('sentiment_volatility', sa.Float(), nullable=True),
    sa.Column('positive_ratio', sa.Float(), nullable=True),
    sa.Column('attention_index', sa.Float(), nullable=True),
    sa.Column('hype_acceleration', sa.Float(), nullable=True),
    sa.Column('raw_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_id', 'snapshot_time', 'window_hours', name='uq_title_snapshot')
    )
    op.create_index(op.f('ix_metrics_snapshots_snapshot_time'), 'metrics_snapshots', ['snapshot_time'], unique=False)
    op.create_index(op.f('ix_metrics_snapshots_title_id'), 'metrics_snapshots', ['title_id'], unique=False)
    op.create_index('ix_snapshots_time_title', 'metrics_snapshots', ['snapshot_time', 'title_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshots_time_title', table_name='metrics_snapshots')
    op.drop_index(op.f('ix_metrics_snapshots_title_id'), table_name='metrics_snapshots')
    op.drop_index(op.f('ix_metrics_snapshots_snapshot_time'), table_name='metrics_snapshots')
    op.drop_table('metrics_snapshots')
    op.drop_index('ix_mentions_title_platform', table_name='mentions')
    op.drop_index(op.f('ix_mentions_title_id'), table_name='mentions')
    op.drop_index('ix_mentions_created_at_title', table_name='mentions')
    op.drop_index(op.f('ix_mentions_created_at'), table_name='mentions')
    op.drop_table('mentions')
    op.drop_index(op.f('ix_alerts_title_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_titles_tmdb_id'), table_name='titles')
    op.drop_table('titles')
    # ### end Alembic commands ###
